"""Batched, GPU-accelerated benchmark metrics for the AGFB suite."""

from agfb_metrics.metrics import (
    PIXEL_METRICS,
    MetricEvaluator,
    angular_mae,
    edge_fwhm,
    evaluate_all_metrics,
    evaluate_metrics,
    localization_offset,
    magnitude,
    magnitude_bias,
    masks,
    noise_gain,
    nrmse,
    ridge_mask_from_truth,
    sidelobe_ratio,
    tail_spurious_grad,
    tail_vector_error,
    tangential_normal_leak,
    unit_normal_from_truth,
)

__all__ = [
    "nrmse",
    "angular_mae",
    "tail_vector_error",
    "localization_offset",
    "tangential_normal_leak",
    "magnitude_bias",
    "edge_fwhm",
    "sidelobe_ratio",
    "noise_gain",
    "tail_spurious_grad",
    "MetricEvaluator",
    "PIXEL_METRICS",
    "evaluate_metrics",
    "evaluate_all_metrics",
    "magnitude",
    "masks",
    "ridge_mask_from_truth",
    "unit_normal_from_truth",
]
